tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bash-completion"
brew "coreutils"
brew "go"
brew "jq"
brew "packer"
brew "php", restart_service: true
brew "tmux"
brew "tree"
cask "clipy"
cask "font-cica"
